using ForgeBlueprint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ForgeBlueprint.Services
{
    public sealed class FootstepsFmodStudioScriptBuilder
    {
        public string Build(BlueprintDefinition blueprint, FootstepsBlueprintOptions options)
        {
            if (blueprint == null)
                throw new ArgumentNullException(nameof(blueprint));

            if (options == null)
                throw new ArgumentNullException(nameof(options));

            string rawPrefix = string.IsNullOrWhiteSpace(options.NamingPrefix)
                ? "character"
                : options.NamingPrefix.Trim();

            string displayPrefix = ToDisplayPrefix(rawPrefix);
            string eventName = $"Footsteps_{displayPrefix}";
            string menuItemName = $"ForgeBlueprint/Create {eventName}";
            List<string> surfaces = options.GetSurfaceNames();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Generated by ForgeBlueprint for FMOD Studio scripting.");
            sb.AppendLine("// Copy this file into an FMOD Studio Scripts folder and run Scripts > Reload.");
            sb.AppendLine("// Then execute the created menu item from the Scripts menu.");
            sb.AppendLine();
            sb.AppendLine("(function () {");
            sb.AppendLine($"    var eventName = {Js(eventName)};");
            sb.AppendLine($"    var displayPrefix = {Js(displayPrefix)};");
            sb.AppendLine($"    var spatialMode = {Js(options.SpatialMode)};");
            sb.AppendLine($"    var includeGear = {(options.IncludeGear ? "true" : "false")};");
            sb.AppendLine($"    var surfaces = {JsArray(surfaces)};");
            sb.AppendLine();

            sb.AppendLine("    function ensureEventFolder(name, parentFolder) {");
            sb.AppendLine("        var folders = studio.project.model.EventFolder.findInstances();");
            sb.AppendLine("        for (var i = 0; i < folders.length; i++) {");
            sb.AppendLine("            if (folders[i].name === name && folders[i].folder === parentFolder) {");
            sb.AppendLine("                return folders[i];");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var folder = studio.project.create('EventFolder');");
            sb.AppendLine("        folder.name = name;");
            sb.AppendLine("        folder.folder = parentFolder;");
            sb.AppendLine("        return folder;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    function findEvent(name, folder) {");
            sb.AppendLine("        var events = studio.project.model.Event.findInstances();");
            sb.AppendLine("        for (var i = 0; i < events.length; i++) {");
            sb.AppendLine("            if (events[i].name === name && events[i].folder === folder) {");
            sb.AppendLine("                return events[i];");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    function findChildBus(name, parentBus) {");
            sb.AppendLine("        var buses = studio.project.model.MixerGroup.findInstances();");
            sb.AppendLine("        for (var i = 0; i < buses.length; i++) {");
            sb.AppendLine("            if (buses[i].name === name && buses[i].output === parentBus) {");
            sb.AppendLine("                return buses[i];");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    function ensureBus(name, parentBus) {");
            sb.AppendLine("        var existing = findChildBus(name, parentBus);");
            sb.AppendLine("        if (existing) {");
            sb.AppendLine("            return existing;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var bus = studio.project.create('MixerGroup');");
            sb.AppendLine("        bus.name = name;");
            sb.AppendLine("        bus.output = parentBus;");
            sb.AppendLine("        return bus;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    function addSurfaceTracks(eventObject) {");
            sb.AppendLine("        for (var i = 0; i < surfaces.length; i++) {");
            sb.AppendLine("            eventObject.addGroupTrack(surfaces[i]);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (includeGear) {");
            sb.AppendLine("            eventObject.addGroupTrack('Gear');");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    function buildFootstepsEvent() {");
            sb.AppendLine("        var charactersFolder = ensureEventFolder('Characters', studio.project.workspace.masterEventFolder);");
            sb.AppendLine("        var characterFolder = ensureEventFolder(displayPrefix, charactersFolder);");
            sb.AppendLine("        var footstepsFolder = ensureEventFolder('Footsteps', characterFolder);");
            sb.AppendLine();
            sb.AppendLine("        var sfxBus = ensureBus('SFX', studio.project.workspace.mixer.masterBus);");
            sb.AppendLine("        var charactersBus = ensureBus('Characters', sfxBus);");
            sb.AppendLine("        var footstepsBus = ensureBus('Footsteps', charactersBus);");
            sb.AppendLine();
            sb.AppendLine("        var existingEvent = findEvent(eventName, footstepsFolder);");
            sb.AppendLine("        if (existingEvent) {");
            sb.AppendLine("            studio.window.navigateTo(existingEvent);");
            sb.AppendLine("            alert('An event named ' + eventName + ' already exists in Characters/' + displayPrefix + '/Footsteps.');");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var eventObject = studio.project.create('Event');");
            sb.AppendLine("        eventObject.name = eventName;");
            sb.AppendLine("        eventObject.folder = footstepsFolder;");
            sb.AppendLine("        eventObject.mixerInput.output = footstepsBus;");
            sb.AppendLine();
            sb.AppendLine("        if (spatialMode === '3D') {");
            sb.AppendLine("            try {");
            sb.AppendLine("                eventObject.masterTrack.mixerGroup.effectChain.addEffect('SpatialiserEffect');");
            sb.AppendLine("            } catch (e) {");
            sb.AppendLine("                console.log('Could not add SpatialiserEffect automatically: ' + e);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        try {");
            sb.AppendLine("            var surfacesParameter = eventObject.addGameParameter({");
            sb.AppendLine("                name: 'Surfaces',");
            sb.AppendLine("                type: studio.project.parameterType.UserEnumeration,");
            sb.AppendLine("                enumerationLabels: surfaces,");
            sb.AppendLine("                initialValue: 0");
            sb.AppendLine("            });");
            sb.AppendLine();
            sb.AppendLine("            if (surfacesParameter && surfacesParameter.preset) {");
            sb.AppendLine("                surfacesParameter.preset.initialValue = 0;");
            sb.AppendLine("            }");
            sb.AppendLine("        } catch (e) {");
            sb.AppendLine("            console.log('Could not create Surfaces parameter automatically: ' + e);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        addSurfaceTracks(eventObject);");
            sb.AppendLine();
            sb.AppendLine("        if (!eventObject.isValid) {");
            sb.AppendLine("            alert('ForgeBlueprint created an invalid FMOD event. Please undo the change and review the script.');");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        studio.window.navigateTo(eventObject);");
            sb.AppendLine("        alert('Created ' + eventName + ' and routed it to bus:/SFX/Characters/Footsteps with a Surfaces parameter and ' + surfaces.length + ' surface tracks' + (includeGear ? ' plus Gear.' : '.'));");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    studio.menu.addMenuItem({");
            sb.AppendLine($"        name: {Js(menuItemName)},");
            sb.AppendLine("        execute: buildFootstepsEvent");
            sb.AppendLine("    });");
            sb.AppendLine("})();");

            return sb.ToString();
        }

        private static string ToDisplayPrefix(string rawPrefix)
        {
            if (string.IsNullOrWhiteSpace(rawPrefix))
                return "Character";

            string[] parts = rawPrefix
                .Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);

            if (parts.Length == 0)
                return "Character";

            return string.Concat(parts.Select(part => char.ToUpperInvariant(part[0]) + part.Substring(1).ToLowerInvariant()));
        }

        private static string Js(string value)
        {
            string safe = (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");

            return $"\"{safe}\"";
        }

        private static string JsArray(IEnumerable<string> values)
        {
            return "[" + string.Join(", ", values.Select(Js)) + "]";
        }
    }
}