using ForgeBlueprint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ForgeBlueprint.Services
{
    public sealed class Ui2dFmodStudioScriptBuilder
    {
        public string Build(BlueprintDefinition blueprint, Ui2dBlueprintOptions options)
        {
            if (blueprint == null)
                throw new ArgumentNullException(nameof(blueprint));

            if (options == null)
                throw new ArgumentNullException(nameof(options));

            List<string> eventNames = options.GetAllEventNames();
            if (eventNames.Count == 0)
                throw new InvalidOperationException("UI 2D Starter needs at least one UI event selected or added.");

            const string menuItemName = "ForgeBlueprint/Create UI 2D Starter";

            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// Generated by ForgeBlueprint for FMOD Studio scripting.");
            sb.AppendLine("// Copy this file into an FMOD Studio Scripts folder and run Scripts > Reload.");
            sb.AppendLine("// Then execute the created menu item from the Scripts menu.");
            sb.AppendLine();
            sb.AppendLine("(function () {");
            sb.AppendLine($"    var eventNames = {JsArray(eventNames)};");
            sb.AppendLine();
            sb.AppendLine("    function ensureEventFolder(name, parentFolder) {");
            sb.AppendLine("        var folders = studio.project.model.EventFolder.findInstances();");
            sb.AppendLine("        for (var i = 0; i < folders.length; i++) {");
            sb.AppendLine("            if (folders[i].name === name && folders[i].folder === parentFolder) {");
            sb.AppendLine("                return folders[i];");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var folder = studio.project.create('EventFolder');");
            sb.AppendLine("        folder.name = name;");
            sb.AppendLine("        folder.folder = parentFolder;");
            sb.AppendLine("        return folder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    function findEvent(name, folder) {");
            sb.AppendLine("        var events = studio.project.model.Event.findInstances();");
            sb.AppendLine("        for (var i = 0; i < events.length; i++) {");
            sb.AppendLine("            if (events[i].name === name && events[i].folder === folder) {");
            sb.AppendLine("                return events[i];");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    function buildUiEvents() {");
            sb.AppendLine("        var uiFolder = ensureEventFolder('UI', studio.project.workspace.masterEventFolder);");
            sb.AppendLine("        var createdEvents = [];");
            sb.AppendLine("        var skippedEvents = [];");
            sb.AppendLine();
            sb.AppendLine("        for (var i = 0; i < eventNames.length; i++) {");
            sb.AppendLine("            var currentName = eventNames[i];");
            sb.AppendLine("            var existingEvent = findEvent(currentName, uiFolder);");
            sb.AppendLine("            if (existingEvent) {");
            sb.AppendLine("                skippedEvents.push(currentName);");
            sb.AppendLine("                continue;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var eventObject = studio.project.create('Event');");
            sb.AppendLine("            eventObject.name = currentName;");
            sb.AppendLine("            eventObject.folder = uiFolder;");
            sb.AppendLine("            createdEvents.push(currentName);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        studio.window.navigateTo(uiFolder);");
            sb.AppendLine();
            sb.AppendLine("        if (createdEvents.length === 0) {");
            sb.AppendLine("            alert('No UI events were created because they already exist.');");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var message = 'Created ' + createdEvents.length + ' UI events in /UI:\\n- ' + createdEvents.join('\\n- ');");
            sb.AppendLine("        if (skippedEvents.length > 0) {");
            sb.AppendLine("            message += '\\n\\nSkipped existing events:\\n- ' + skippedEvents.join('\\n- ');");
            sb.AppendLine("        }");
            sb.AppendLine("        alert(message);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    studio.menu.addMenuItem({");
            sb.AppendLine($"        name: {Js(menuItemName)},");
            sb.AppendLine("        execute: buildUiEvents");
            sb.AppendLine("    });");
            sb.AppendLine("})();");

            return sb.ToString();
        }

        private static string Js(string value)
        {
            string safe = (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");

            return $"\"{safe}\"";
        }

        private static string JsArray(IEnumerable<string> values)
        {
            return "[" + string.Join(", ", values.Select(Js)) + "]";
        }
    }
}